datetime:
  special_formats:
    minute:
      - "YYYYMMDDHHmm"
      - "YYYY-MM-DD HH:mm"
      - "DD/MM/YY HH:mm"
      - "DD.MM.YYYY HH:mm"
      - "HH:mm YYYY-MM-DD"
      - "HH:mm DD/MM/YYYY"
      - "HH:mm DD.MM.YYYY"
      - "YYYY-M-D H:mm"
      - "YYYY-MM-D H:mm"
      - "YYYY-M-DD H:mm"
      - "YYYY-M-D HH:mm"
      - "YYYY-MM-DD H:mm"
      - "YYYY-MM-D HH:mm"
      - "YYYY-M-DD HH:mm"
      - "D/M/YYYY HH:mm"
      - "D/MM/YYYY H:mm"
      - "DD/M/YYYY H:mm"
      - "D/MM/YYYY HH:mm"
      - "DD/M/YYYY HH:mm"
      - "DD/MM/YYYY H:mm"
      - "D.M.YYYY H:mm"
      - "DD.M.YYYY H:mm"
      - "D.MM.YYYY H:mm"
      - "D.M.YYYY HH:mm"
      - "DD.MM.YYYY H:mm"
      - "DD.M.YYYY HH:mm"
      - "D.MM.YYYY HH:mm"
      - "H:mm YYYY-M-D"
      - "H:mm YYYY-MM-D"
      - "H:mm YYYY-M-DD"
      - "HH:mm YYYY-M-D"
      - "H:mm YYYY-MM-DD"
      - "HH:mm YYYY-MM-D"
      - "HH:mm YYYY-M-DD"
      - "HH:mm D/M/YYYY"
      - "H:mm D/MM/YYYY"
      - "H:mm DD/M/YYYY"
      - "HH:mm D/MM/YYYY"
      - "HH:mm DD/M/YYYY"
      - "H:mm DD/MM/YYYY"
      - "H:mm D.M.YYYY"
      - "H:mm DD.M.YYYY"
      - "H:mm D.MM.YYYY"
      - "HH:mm D.M.YYYY"
      - "H:mm DD.MM.YYYY"
      - "HH:mm DD.M.YYYY"
      - "HH:mm D.MM.YYYY"        
    hour:
      - "YYYYMMDDHH"
      - "YYYY-MM-DD HH[h]"
      - "DD/MM/YYYY HH[h]"
      - "DD.MM.YYYY HH[h]"
      - "YYYY-M-D H[h]"
      - "YYYY-MM-D H[h]"
      - "YYYY-M-DD H[h]"
      - "YYYY-M-D HH[h]"
      - "YYYY-MM-DD H[h]"
      - "YYYY-MM-D HH[h]"
      - "YYYY-M-DD HH[h]"
      - "D/M/YYYY H[h]"
      - "D/M/YYYY HH[h]"
      - "D/MM/YYYY H[h]"
      - "DD/M/YYYY H[h]"
      - "D/MM/YYYY HH[h]"
      - "DD/M/YYYY HH[h]"
      - "DD/MM/YYYY H[h]"
      - "D.M.YYYY H[h]"
      - "DD.M.YYYY H[h]"
      - "D.MM.YYYY H[h]"
      - "D.M.YYYY HH[h]"
      - "DD.MM.YYYY H[h]"
      - "DD.M.YYYY HH[h]"
      - "D.MM.YYYY HH[h]"
    day:
      - "YYYYMMDD"
      - "YYYY-MM-DD"
      - "DD/MM/YYYY"
      - "DD.MM.YYYY"
      - "YYYY-M-D"
      - "YYYY-MM-D"
      - "YYYY-M-DD"
      - "D/M/YYYY"
      - "D/MM/YYYY"
      - "DD/M/YYYY"
      - "D.M.YYYY"
      - "DD.M.YYYY"
      - "D.MM.YYYY"        
    month:
      - "YYYYMM"
      - "YYYY-MM"
      - "MM/YYYY"
      - "M/YYYY"
      - "YYYY/MM"
      - "YYYY/M"
